services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digigotchi-dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: npm run dev
    tty: true
    stdin_open: true
