import type { StatusEffectType } from "./status-effects";
import type { AttackDirectionType } from "./direction";

export type AttackSlotConfig = {
  name: string;
  damage: number;
  range?: number;
  area?: number;
  cooldownMs: number;
  animation: string;
  projectileColor?: number;
  statusEffect?: StatusEffectType;
  shakeIntensity?: number;
  invulnerableFramesMs?: number;
  reflectProjectiles?: boolean;
  attackType: AttackDirectionType;
  description: string;
};

export type PlayableSpeciesCombatProfile = {
  speciesId: string;
  displayName: string;
  role: string;
  element: "fogo" | "gelo" | "eletricidade" | "neutro";
  baseSpeed: number;
  basic1: AttackSlotConfig;
  basic2: AttackSlotConfig;
  special: AttackSlotConfig;
};

export const PLAYABLE_COMBAT_PROFILES: Record<string, PlayableSpeciesCombatProfile> = {
  agumon: {
    speciesId: "agumon",
    displayName: "Agumon",
    role: "Ofensivo Equilibrado",
    element: "fogo",
    baseSpeed: 105,
    basic1: {
      name: "Golpe de Garra",
      damage: 18,
      range: 48,
      cooldownMs: 380,
      animation: "player-attack-basic-1",
      attackType: "DIRECTIONAL_MELEE",
      description: "Golpe físico frontal veloz.",
    },
    basic2: {
      name: "Chama Bebê",
      damage: 24,
      range: 240,
      cooldownMs: 650,
      animation: "player-attack-basic-2",
      projectileColor: 0xff6600,
      statusEffect: "burn",
      attackType: "DIRECTIONAL_PROJECTILE",
      description: "Disparo ígneo com chance de queimar o alvo.",
    },
    special: {
      name: "Bafo de Pimenta",
      damage: 48,
      area: 96,
      cooldownMs: 2400,
      animation: "player-attack-special",
      shakeIntensity: 0.008,
      attackType: "RADIAL_AREA",
      description: "Explosão de fogo devastadora em área.",
    },
  },
  veemon: {
    speciesId: "veemon",
    displayName: "Veemon",
    role: "Velocidade e Combos",
    element: "neutro",
    baseSpeed: 125,
    basic1: {
      name: "Vee-Punch",
      damage: 14,
      range: 44,
      cooldownMs: 260,
      animation: "player-attack-basic-1",
      attackType: "DIRECTIONAL_MELEE",
      description: "Socos ultrarrápidos com cancelamento ágil.",
    },
    basic2: {
      name: "Vee-Laser",
      damage: 20,
      range: 300,
      cooldownMs: 500,
      animation: "player-attack-basic-2",
      projectileColor: 0x00e5ff,
      attackType: "DIRECTIONAL_PROJECTILE",
      description: "Feixe de plasma digital de longo alcance.",
    },
    special: {
      name: "Vee-Headbutt Turbinado",
      damage: 42,
      area: 80,
      cooldownMs: 1900,
      animation: "player-attack-special",
      invulnerableFramesMs: 250,
      shakeIntensity: 0.006,
      attackType: "DIRECTIONAL_SPECIAL",
      description: "Investida rápida com invulnerabilidade momentânea.",
    },
  },
  gabumon: {
    speciesId: "gabumon",
    displayName: "Gabumon",
    role: "Tático e Controle",
    element: "gelo",
    baseSpeed: 98,
    basic1: {
      name: "Chifre Perfurante",
      damage: 20,
      range: 52,
      cooldownMs: 420,
      animation: "player-attack-basic-1",
      attackType: "DIRECTIONAL_MELEE",
      description: "Investida perfurante com alto impacto.",
    },
    basic2: {
      name: "Blue Blaster",
      damage: 22,
      range: 220,
      cooldownMs: 700,
      animation: "player-attack-basic-2",
      projectileColor: 0x3399ff,
      statusEffect: "slow",
      attackType: "DIRECTIONAL_PROJECTILE",
      description: "Sopro congelante que reduz a velocidade inimiga.",
    },
    special: {
      name: "Garuru-Aura",
      damage: 38,
      area: 110,
      cooldownMs: 2600,
      animation: "player-attack-special",
      reflectProjectiles: true,
      shakeIntensity: 0.005,
      attackType: "RADIAL_AREA",
      description: "Aura mística que repele inimigos e anula disparos.",
    },
  },
  wargreymon: {
    speciesId: "wargreymon",
    displayName: "WarGreymon",
    role: "Hiper-Ofensivo Mega",
    element: "fogo",
    baseSpeed: 110,
    basic1: {
      name: "Garra Dramon Killer",
      damage: 38,
      range: 60,
      cooldownMs: 340,
      animation: "player-attack-basic-1",
      attackType: "DIRECTIONAL_MELEE",
      description: "Corte devastador com as garras anti-dragão.",
    },
    basic2: {
      name: "Grande Tornado",
      damage: 45,
      range: 280,
      cooldownMs: 700,
      animation: "player-attack-basic-2",
      projectileColor: 0xff8800,
      statusEffect: "burn",
      attackType: "DIRECTIONAL_PROJECTILE",
      description: "Projétil furioso de chamas giratórias.",
    },
    special: {
      name: "Força Terra",
      damage: 95,
      area: 140,
      cooldownMs: 3200,
      animation: "player-attack-special",
      shakeIntensity: 0.015,
      attackType: "RADIAL_AREA",
      description: "Condensação de energia solar titânica devastadora.",
    },
  },
  weregarurumon: {
    speciesId: "weregarurumon",
    displayName: "WereGarurumon",
    role: "Lutador Veloz & Crítico",
    element: "gelo",
    baseSpeed: 128,
    basic1: {
      name: "Garras do Lobo",
      damage: 32,
      range: 55,
      cooldownMs: 280,
      animation: "player-attack-basic-1",
      attackType: "DIRECTIONAL_MELEE",
      description: "Sequência veloz de cortes cortantes.",
    },
    basic2: {
      name: "Garuru Kick Crescente",
      damage: 36,
      range: 260,
      cooldownMs: 600,
      animation: "player-attack-basic-2",
      projectileColor: 0x44ccff,
      statusEffect: "slow",
      attackType: "DIRECTIONAL_PROJECTILE",
      description: "Onda de choque cortante em meia-lua.",
    },
    special: {
      name: "Chute Moonsault",
      damage: 80,
      area: 120,
      cooldownMs: 2800,
      animation: "player-attack-special",
      invulnerableFramesMs: 300,
      shakeIntensity: 0.01,
      attackType: "DIRECTIONAL_SPECIAL",
      description: "Acrobacia aérea com impacto congelante e invulnerabilidade momentânea.",
    },
  },
  xvmon: {
    speciesId: "xvmon",
    displayName: "ExVeemon",
    role: "Combatente Aéreo Ágil",
    element: "neutro",
    baseSpeed: 120,
    basic1: {
      name: "X-Soco Forte",
      damage: 24,
      range: 50,
      cooldownMs: 320,
      animation: "player-attack-basic-1",
      attackType: "DIRECTIONAL_MELEE",
      description: "Golpe frontal com punho energizado.",
    },
    basic2: {
      name: "X-Laser",
      damage: 30,
      range: 320,
      cooldownMs: 580,
      animation: "player-attack-basic-2",
      projectileColor: 0x00f0ff,
      attackType: "DIRECTIONAL_PROJECTILE",
      description: "Disparo concentrado em forma de X.",
    },
    special: {
      name: "Hearty Shatter",
      damage: 62,
      area: 105,
      cooldownMs: 2300,
      animation: "player-attack-special",
      shakeIntensity: 0.008,
      attackType: "RADIAL_AREA",
      description: "Descarga de energia corporal explosiva.",
    },
  },
  garurumon: {
    speciesId: "garurumon",
    displayName: "Garurumon",
    role: "Predador Gélido",
    element: "gelo",
    baseSpeed: 115,
    basic1: {
      name: "Investida Cortante",
      damage: 22,
      range: 50,
      cooldownMs: 350,
      animation: "player-attack-basic-1",
      attackType: "DIRECTIONAL_MELEE",
      description: "Bote veloz com mordida rápida.",
    },
    basic2: {
      name: "Fox Fire",
      damage: 28,
      range: 260,
      cooldownMs: 650,
      animation: "player-attack-basic-2",
      projectileColor: 0x66bbff,
      statusEffect: "slow",
      attackType: "DIRECTIONAL_PROJECTILE",
      description: "Chama azul fria que reduz a velocidade inimiga.",
    },
    special: {
      name: "Freeze Fang",
      damage: 56,
      area: 95,
      cooldownMs: 2400,
      animation: "player-attack-special",
      shakeIntensity: 0.007,
      attackType: "RADIAL_AREA",
      description: "Explosão de estacas gélidas ao redor.",
    },
  },
  geogreymon: {
    speciesId: "geogreymon",
    displayName: "GeoGreymon",
    role: "Colosso de Fogo",
    element: "fogo",
    baseSpeed: 100,
    basic1: {
      name: "Impulso do Chifre",
      damage: 26,
      range: 54,
      cooldownMs: 400,
      animation: "player-attack-basic-1",
      attackType: "DIRECTIONAL_MELEE",
      description: "Cabeçada pesada com os chifres blindados.",
    },
    basic2: {
      name: "Mega Tiro",
      damage: 32,
      range: 280,
      cooldownMs: 700,
      animation: "player-attack-basic-2",
      projectileColor: 0xff4500,
      statusEffect: "burn",
      attackType: "DIRECTIONAL_PROJECTILE",
      description: "Disparo contínuo de projéteis de fogo denso.",
    },
    special: {
      name: "Mega Chama Vulcânica",
      damage: 68,
      area: 115,
      cooldownMs: 2600,
      animation: "player-attack-special",
      shakeIntensity: 0.012,
      attackType: "RADIAL_AREA",
      description: "Erupção concentrada de chamas ao redor.",
    },
  },
  etemon: {
    speciesId: "etemon",
    displayName: "Etemon",
    role: "Trapaceiro Rítmico",
    element: "eletricidade",
    baseSpeed: 112,
    basic1: {
      name: "Garra de Macaco",
      damage: 22,
      range: 46,
      cooldownMs: 320,
      animation: "player-attack-basic-1",
      attackType: "DIRECTIONAL_MELEE",
      description: "Bofetadas cômicas e desestabilizantes.",
    },
    basic2: {
      name: "Dark Network Disparo",
      damage: 26,
      range: 250,
      cooldownMs: 620,
      animation: "player-attack-basic-2",
      projectileColor: 0x9933ff,
      statusEffect: "shock",
      attackType: "DIRECTIONAL_PROJECTILE",
      description: "Esfera de dados corrompidos com carga elétrica.",
    },
    special: {
      name: "Serenata do Amor",
      damage: 55,
      area: 120,
      cooldownMs: 2500,
      animation: "player-attack-special",
      shakeIntensity: 0.009,
      attackType: "RADIAL_AREA",
      description: "Ondas sonoras desafinadas que atordoam inimigos na área.",
    },
  },
  metaletemon: {
    speciesId: "metaletemon",
    displayName: "MetalEtemon",
    role: "Tanque Metálico Punk",
    element: "eletricidade",
    baseSpeed: 104,
    basic1: {
      name: "Mega Soco Cromado",
      damage: 36,
      range: 52,
      cooldownMs: 380,
      animation: "player-attack-basic-1",
      attackType: "DIRECTIONAL_MELEE",
      description: "Golpe pesado com blindagem de metal reforçado.",
    },
    basic2: {
      name: "Dark Spirits Deluxe",
      damage: 42,
      range: 290,
      cooldownMs: 680,
      animation: "player-attack-basic-2",
      projectileColor: 0xbb00ff,
      statusEffect: "shock",
      attackType: "DIRECTIONAL_PROJECTILE",
      description: "Relâmpago sombrio concentrado de alta voltagem.",
    },
    special: {
      name: "Banana Slip Suprema",
      damage: 85,
      area: 130,
      cooldownMs: 3000,
      animation: "player-attack-special",
      invulnerableFramesMs: 250,
      shakeIntensity: 0.014,
      attackType: "RADIAL_AREA",
      description: "Impacto sonoro e bananas de ouro que eletrificam o solo.",
    },
  },
  kingetemon: {
    speciesId: "kingetemon",
    displayName: "KingEtemon",
    role: "Monarca Excêntrico",
    element: "eletricidade",
    baseSpeed: 108,
    basic1: {
      name: "Bofetada Real",
      damage: 34,
      range: 50,
      cooldownMs: 350,
      animation: "player-attack-basic-1",
      attackType: "DIRECTIONAL_MELEE",
      description: "Tapa monárquico com autoridade absoluta.",
    },
    basic2: {
      name: "Rede Imperial de Choque",
      damage: 40,
      range: 300,
      cooldownMs: 650,
      animation: "player-attack-basic-2",
      projectileColor: 0xffd700,
      statusEffect: "shock",
      attackType: "DIRECTIONAL_PROJECTILE",
      description: "Rajada de cabos dourados eletrificados.",
    },
    special: {
      name: "Grande Concerto Régio",
      damage: 82,
      area: 135,
      cooldownMs: 2900,
      animation: "player-attack-special",
      shakeIntensity: 0.012,
      attackType: "RADIAL_AREA",
      description: "Performance real ensurdecedora com rajadas de choque em área.",
    },
  },
  flamedramon: {
    speciesId: "flamedramon",
    displayName: "Flamedramon",
    role: "Investida Ígnea Veloz",
    element: "fogo",
    baseSpeed: 122,
    basic1: {
      name: "Fogo na Garra",
      damage: 28,
      range: 52,
      cooldownMs: 310,
      animation: "player-attack-basic-1",
      attackType: "DIRECTIONAL_MELEE",
      description: "Cortes flamejantes em rápida sucessão.",
    },
    basic2: {
      name: "Fire Rocket",
      damage: 35,
      range: 300,
      cooldownMs: 620,
      animation: "player-attack-basic-2",
      projectileColor: 0xff5500,
      statusEffect: "burn",
      attackType: "DIRECTIONAL_PROJECTILE",
      description: "Disparo potente em formato de foguete de fogo.",
    },
    special: {
      name: "Escudo Flamejante Explosivo",
      damage: 72,
      area: 110,
      cooldownMs: 2500,
      animation: "player-attack-special",
      invulnerableFramesMs: 200,
      shakeIntensity: 0.01,
      attackType: "RADIAL_AREA",
      description: "Aura de fogo em espiral que incinera inimigos ao redor.",
    },
  },
};

export function getSpeciesCombatProfile(speciesId: string): PlayableSpeciesCombatProfile {
  return PLAYABLE_COMBAT_PROFILES[speciesId] ?? PLAYABLE_COMBAT_PROFILES.agumon;
}
